services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: tabley-app
    container_name: tabley-app
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"
      - "5173:5173" # Vite用

  db:
    image: mysql:8.0
    container_name: tabley-db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: tabley
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_USER: tabley_user
    volumes:
      - dbdata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: tabley-phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: tabley_user
      PMA_PASSWORD: root
    depends_on:
      - db

volumes:
  dbdata: